Blog app - integration specs for views and fix n+1 problems
Jrmcuervo/Blog-app_ror pull request #8
Opened 2023-08-31 19:28 UTC by Jrmcuervo

In this project we :

- Added integration specs using Capybara and Rspec
- Tested views: users/index, users/show, posts/index, and posts/view
- Checked if correct content is displayed on each page
- Checked if all links on the pages are working
- Fixed n+1 problem in the posts/index view

**Before**

![before 1](https://github.com/Jrmcuervo/Blog-app_ror/assets/116699473/6bea00d5-fd3b-40df-bd21-09b2d190798f)

![before 2](https://github.com/Jrmcuervo/Blog-app_ror/assets/116699473/23e46b3d-4f6c-4535-a475-ee02a00c41aa)

**After**
![after](https://github.com/Jrmcuervo/Blog-app_ror/assets/116699473/a0df3a55-01d6-4dcf-9886-c6d8f8ada39f)

2023-08-31 21:01 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Some requirements fufilled. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] Kindly look into some previous tests which are failing at this moment

![error-1](https://github.com/Jrmcuervo/Blog-app_ror/assets/26597432/5f507aa2-6b3b-480a-b6fd-cafb58da6879)

![error-2](https://github.com/Jrmcuervo/Blog-app_ror/assets/26597432/c0687df2-f38f-44d9-a7ac-e4741672758f)


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 21:01 UTC, Qoosim commented on spec/views/users/users_index_spec.rb
> +end
- [ ] Great job team. There're few tests you still need to write for your user index page. Kindly check below screenshot to see the remaining tests.

### Project requirements.
![user-index](https://github.com/Jrmcuervo/Blog-app_ror/assets/26597432/6777a30c-2df3-47a3-8a6a-33bb8be243d5)

2023-08-31 21:01 UTC, Qoosim commented on spec/views/users/users_show_spec.rb
> +  end
- [ ] Some tests are yet to be written here too. Kindly check the underlined points and write their respective tests for them.

### Project requirement
![user-show](https://github.com/Jrmcuervo/Blog-app_ror/assets/26597432/48b43d2c-6e59-453c-af0c-3510abaef312)

2023-08-31 21:01 UTC, Qoosim commented on spec/views/posts/show_spec.rb
> +equire 'rails_helper'
- [ ] There's a spelling error here. Kindly change that tp `require` instead of `equire`

2023-09-02 01:08 UTC, jerryowusu requested changes
Hi @Jrmcuervo 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close](https://github.com/Jrmcuervo/Blog-app_ror/assets/65233860/f7cdd6e7-6b39-461c-b28a-6e63314931b1)

 ## Highlights
Used gitflow :+1: 
Made some requested changes :+1: 

 ## Required Changes ♻️

- [ ] As shown below, the newly migrated files are causing undefinedObject errors and duplicateObject errors that is preventing the database to be set up properly. Kindly check and fix all this issues. 

![Screenshot from 2023-09-02 01-04-21](https://github.com/Jrmcuervo/Blog-app_ror/assets/65233860/7b81cad5-a4eb-4a54-9839-bff30fd79bf7)

![Screenshot from 2023-09-02 01-04-30](https://github.com/Jrmcuervo/Blog-app_ror/assets/65233860/ff434026-72e6-4eae-9a2c-c9eab8d26a48)



![Screenshot from 2023-09-02 01-04-12](https://github.com/Jrmcuervo/Blog-app_ror/assets/65233860/cdab2de1-e6f6-41f7-aa0b-0d5eef8dda10)



_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-02 01:08 UTC, jerryowusu commented on spec/views/users/users_show_spec.rb
> +    end
As requested by the previous reviewer, you are missing some of the tests in this file. Kindly check the underlined tests are added and make sure they are all passing before submitting for review. :pray: 

![Screenshot from 2023-09-02 00-40-16](https://github.com/Jrmcuervo/Blog-app_ror/assets/65233860/53fa7186-684c-436a-bfbe-9089a5b8fe5c)

2023-09-02 01:25 UTC, Jrmcuervo commented on spec/views/users/users_show_spec.rb
> +    end
Hello! @jerryowusu  Thanks for the feedback, if you could review the show_spec.rb file in the spec/users/show_spec.rb path, there are the rest of the tests, if you do the test you will see that there are 33 tests being performed, now I fix the problem with migrations, thanks and greetings!

By the way those tests were there from the beginning @Qoosim

2023-09-02 01:53 UTC, jerryowusu approved these changes
Hi @Jrmcuervo 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![CookedDelectableDolphin-size_restricted](https://github.com/Jrmcuervo/Blog-app_ror/assets/65233860/57a83d5f-c419-4aba-bb30-cdb0222b740e)


## Highlights
All tests are passing :+1: 
Great effort in making the requested changes :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-02 01:55 UTC, merged